name: Build, Test and Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake lcov gcovr python3-pip
          pip install gcovr

      - name: Configure and Build
        run: |
          rm -rf build && mkdir -p build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=ON
          cmake --build .

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Debug Coverage Files
        run: |
          cd build
          find . -name "*.gcda"
          echo "Checking for coverage files..."

      - name: Generate Coverage Report
        run: |
          cd build
          lcov --capture --directory . --output-file coverage.info --ignore-errors mismatch --rc branch_coverage=1 --rc geninfo_unexecuted_blocks=1
          lcov --remove coverage.info '*/tests/*' '*/_deps/*' '/usr/*' --output-file coverage.info
          lcov --list coverage.info || echo "Failed to list coverage.info"



      - name: Check Coverage File
        run: |
          cd build
          ls -l coverage.info || echo "Coverage file not generated"

      - name: Upload Coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./build/coverage.info
          coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}